image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      cd build && make
    command: |
      cd build; conan info .

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080 # VNC for X11 C++ GUI Development
    onOpen: open-preview
  
vscode:
  extensions:
    - ms-vscode.cpptools
